image: chaossumo/tf-provider-pipeline-runner:2022-05-11

pipelines:
  default:
    - step:
        name: Go Lint
        script:
          - golangci-lint run -c .golangci.yml
    - step:
        name: Acceptance Test
        script:
          - TF_ACC=1 go test -v ./provider/tests/
  custom:
    PUBLISH_RELEASE_VERSION_GITHUB:
      - variables:
        - name: VERSION

      - step:
          image:
            hashicorp/terraform:latest
          script:
            - BRANCH_NAME=$(git rev-parse --symbolic-full-name --abbrev-ref HEAD)
            - if [[ $BRANCH_NAME != master ]]; then echo "This can only be performed on master branch" && exit 1; fi
            - git pull origin master
            - git remote add github git@github.com:ChaosSearch/terraform-provider-ChaosSearch.git
            - git tag ${VERSION} && git push github ${VERSION}
            - git push github master

    SYNC_RELEASE_VERSION_BITBUCKET:
      - variables:
        - name: VERSION
      - step:
          image:
            hashicorp/terraform:latest
          script:
            - BRANCH_NAME=$(git rev-parse --symbolic-full-name --abbrev-ref HEAD)
            - if [[ $BRANCH_NAME != master ]]; then echo "This can only be performed on master branch" && exit 1; fi
            - git remote add github git@github.com:ChaosSearch/terraform-provider-ChaosSearch.git
            - git pull github master
            - git tag ${VERSION} && git push github ${VERSION}
            - git push origin master